# Generated by Django 4.2.7 on 2023-12-10 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='user_name',
        ),
    ]
